name: easygo
channels:
    - conda-forge
    - defaults
    - gimli
dependencies:
    - python
    - pandas=1.3.4
    - pygimli=1.2.4
    - gempy
    - gemgis
    - pymc3
    - theano-pymc
    - mkl
    - mkl-service
    - scipy
    - jupyterlab